default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  database: sample_app_development

#development:
#  <<: *default
#  encoding: unicode
#  host: db
#  username: postgres
#  password:
#  database: sample_rails_app_db

test:
  <<: *default
  database: sample_app_test
  username: <%= ENV['POSTGRESQL_ENV_POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRESQL_ENV_POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRESQL_ENV_POSTGRES_HOST'] || 'localhost' %>

#test:
#  <<: *default
#  encoding: unicode
#  host: db
#  username: postgres
#  password:
#  database: sample_rails_app_db_test

production:
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: sample_app_production
  username: sample_app
  password: <%= ENV['SAMPLE_APP_DATABASE_PASSWORD'] %>